initial
RIBorisov/gophermart pull request #1
Opened 2024-07-04 19:25 UTC by RIBorisov

2024-07-15 16:40 UTC, s-shpak requested changes

2024-07-15 16:40 UTC, s-shpak commented on cmd/gophermart/main.go
> +	return srv.ListenAndServe()
1. Не все ошибки, возвращаемые этим методом являются ошибками
2. Для gracefult shutdown все горутины должны быть завершены (посмотри в сторону https://pkg.go.dev/golang.org/x/sync/errgroup и https://github.com/s-shpak/webinar-goroutines?tab=readme-ov-file#контекст-и-graceful-shutdown)

2024-07-15 16:40 UTC, s-shpak commented on cmd/gophermart/main.go
> +	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
См. https://pkg.go.dev/os/signal#NotifyContext

2024-07-15 16:40 UTC, s-shpak commented on cmd/gophermart/main.go
> +	srv := &http.Server{
Посмотри какие поля есть в структуре `http.Server` и разберись, какие и как стоит сконфигуровать

2024-07-15 16:40 UTC, s-shpak commented on internal/errs/errors.go
> +package errs
лучше ошибки объявлять в тех пакетах, где они используются

2024-07-15 16:40 UTC, s-shpak commented on internal/storage/storage.go
> +	err := d.pool.QueryRow(ctx, selectStmt, orderNo).Scan(&existedOrderNo, &existedUserID)
1. Здесь нужна транзакция
2. В прниципе, можно обойтись одним запросом

2024-07-15 16:40 UTC, s-shpak commented on internal/service/service.go
> +	list := make([]orders.Order, 0)
Либо длина, либо capacity слайсла должы быть равны соответствующим параметрам `raw`

2024-07-15 16:40 UTC, s-shpak commented on internal/service/service.go
> +	sort.SliceStable(list, func(i, j int) bool {
Здесь не нужна стабильная сортировка

2024-07-15 16:40 UTC, s-shpak commented on internal/storage/storage.go
> +type Store interface {
В Го интерфейс объявляется (как правило) там, где он используется

2024-07-15 16:40 UTC, s-shpak commented on internal/external/accrual/accrual.go
> +				svc.Log.Err("failed get unprocessed orders", err)
Здесь нужен continue

2024-07-15 16:40 UTC, s-shpak commented on internal/external/accrual/accrual.go
> +	go func() {
1. Используй WorkerPool
2. Обработай ситуацию, если сервис присылает `Too many requests`

2024-07-15 16:40 UTC, s-shpak commented on internal/external/accrual/accrual.go
> +					svc.Log.Err("failed fetch order info", err)
`continue`

2024-07-15 16:40 UTC, s-shpak commented on internal/service/service.go
> +	h := sha256.New()
Используй `bcrypt`

2024-07-26 18:54 UTC, s-shpak requested changes
Выдай мне права на репозиторий еще раз, пожалуйста, чтобы я смог позакрывать комменты

2024-07-26 18:54 UTC, s-shpak commented on internal/handlers/balance.go
> +			if err = r.Body.Close(); err != nil {
Боди запросов можно не закрывать (только клиент должен закрывать ответы сервера)

2024-07-26 18:54 UTC, s-shpak commented on internal/service/luhn.go
> +	asciiZero = 48
Эту константу можно не создавать:

```suggestion
	asciiZero = '0'
```

2024-07-26 18:54 UTC, s-shpak commented on internal/storage/migrations/001_users.down.sql
Миграции можно слить в одну

2024-07-26 18:54 UTC, s-shpak commented on cmd/gophermart/main.go
> +					if err := accrual.ProcessOrder(ctx, svc, o, client); err != nil {
Все почти праивльно кроме того, что `TooManyRequests` должен приводить к стопу всех клиентов на указанный интервал времени. Подумай, как это лучше сделать

2024-08-01 21:48 UTC, s-shpak requested changes

2024-08-01 21:48 UTC, s-shpak commented on internal/storage/storage.go
> +type Store interface {
А зачем этот интерфейс здесь ? В основном, стоит всегда возвращать структуры, принимать на вход интерфейсы. Длеать по-другому надо только если есть объективная причина зачем

2024-08-01 21:48 UTC, s-shpak commented on cmd/gophermart/main.go
Уменьши количество кода в `main`

2024-08-02 07:21 UTC, RIBorisov commented on internal/storage/storage.go
> +type Store interface {
Возвращать интерфейсы научили на курсе, когда несколько хранилищ использовалось, я тут забыл поправить

2024-08-02 15:18 UTC, s-shpak approved these changes

2024-08-07 09:26 UTC, merged